behaviors:
  default:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.75
        gamma: 0.99
        demo_path: C:\Users\ridus\Documents\Unity Projects\ML-Racing\ML Racing\Demo
    behavioral_cloning: 
      strength: 0.5
      demo_path: C:\Users\ridus\Documents\Unity Projects\ML-Racing\ML Racing\Demo   
    keep_checkpoints: 5
    max_steps: 5.0e8
    time_horizon: 1000
    summary_freq: 12000

